### ISSUE TITLE
support for python 3

### ISSUE THREAD

**Issue by xylar** [E3SM-Project/a-prime#15]
As the e3sm-unified environment is moving quickly toward python 3 support, and we (meaning mostly @jhkennedy) have just added python 3 support in MPAS-Analysis, a-prime should strongly consider doing the same.

This is something I can help with and maybe @jhkennedy as well.

**Comment by kevans32** [comment]
Yes we are going to do this. Well, @salilmahajan is with help from @jhkennedy.

**Comment by xylar** [comment]
Solution is being worked on in #23

**Comment by kevans32** [comment]
Just ran a case on rhea. @salilmahajan I am missing some files in the case I targeted:
IOError: [Errno 2] No such file or directory: '/lustre/atlas1/cli115/proj-shared/salil/archive/20170502.beta1_05-IEFLX.A_WCYCL1850S.ne30_oECv3_ICG.edison/run/mpas-o_in'
Do you have a complete one for testing I can use too? If not can others point me to one I can transfer to rhea for testing?

**Comment by salilmahajan** [comment]
@kevans32, I did not copy any ocean output on my space on Lustre when I was testing for the enso diags earlier. I just initiated a transfer of the beta3rc10 archive directory using globus. It will be available here when its done: /lustre/atlas1/cli115/proj-shared/salil/archive/20171122.beta3rc10_1850.ne30_oECv3_ICG.edison

**Comment by xylar** [comment]
@kevans32 and @salilmahajan, I think this discussion is probably happening in the wrong place?  Are you testing @milenaveneziani's pull request?  If so, comments should be moved to #24.

**Comment by kevans32** [comment]
Yes done. Sorry there are many open branches that need testing. I will move to the one you specified

**Comment by xylar** [comment]
At this point, I think the plan should be to migrate a-prime capabilities over to e3sm_diags rather than trying to add python 3 support here.
