### ISSUE TITLE
undefined expression errors

### ISSUE THREAD

**Issue by xylar** [E3SM-Project/a-prime#19]
In the atm diagnostics, I'm seeing a lot of errors of the type:
```
No derived variable list found for  FLUT

FLUT derived from:
Traceback (most recent call last):
  File "python/plot_climo.py", line 125, in <module>
    reg = 'global')
  File "/global/u2/x/xylar/acme_work/a-prime/fix_python_formatting/python/read_climo_file.py", line 59, in read_climo_file
    var_expr, var_expr_numpy = get_derived_var_expr(field_name)
  File "/global/u2/x/xylar/acme_work/a-prime/fix_python_formatting/python/get_derived_var_expr.py", line 31, in get_derived_var_expr
    print field_name, 'derived from: ', var_expr.atoms(Symbol)
UnboundLocalError: local variable 'var_expr' referenced before assignment
```
I'm not sure if these errors are catastrophic but it seems like at the very least a more intuitive error handling is needed.

I'm seeing these both in `master` and in my branch `xylar/fix_python_formatting`.

**Comment by milenaveneziani** [comment]
hmm, I didn't see these errors at all yesterday. Where are you running this?

And yes, I am afraid these are catastrophic errors, and I think they occur because 'No derived variable list found for FLUT'.

**Comment by salilmahajan** [comment]
I am taking a look at it now.

**Comment by xylar** [comment]
I'm running on NERSC.  I don't think you would see these errors unless you dig into the log files because the atmosphere scripts don't tell you if they exited with an error. (see #11).

**Comment by milenaveneziani** [comment]
I did look at the log files yesterday, while I was debugging Chris's problem. I remember seeing other errors (due to permissions on the output files), but not this one.
Were you running using beta3 data?

**Comment by kevans32** [comment]
@salilmahajan is also working on better error handling, but it will take a little time to do it properly, so standby a day or two.

**Comment by xylar** [comment]
> @salilmahajan is also working on better error handling, but it will take a little time to do it properly, so standby a day or two.

No rush on my behalf.  I just wanted to report problems I was seeing as I tried out a-prime myself to make sure fixes make it into the next version.

**Comment by milenaveneziani** [comment]
@salilmahajan: when you have a chance, could you please look into these error messages? They don't seem to affect the diagnostics, but it would be good to get rid of them, perhaps in the next PR. Thanks.

**Comment by milenaveneziani** [comment]
As an update, during my recent tests for #34 on edison, I have only seen two instances of this kind of error message:
```
SST derived from:
Traceback (most recent call last):
  File "python/plot_meridional_avg_climo.py", line 260, in <module>
    debug = debug)
  File "python/plot_meridional_avg_climo.py", line 90, in plot_meridional_avg_climo
    debug = debug)
  File "/global/u2/m/milena/a-prime/python/get_reg_meridional_avg_climo.py", line 43, in get_reg_meridional_avg_climo
    debug = debug)
  File "/global/u2/m/milena/a-prime/python/read_climo_file.py", line 59, in read_climo_file
    var_expr, var_expr_numpy = get_derived_var_expr(field_name)
  File "/global/u2/m/milena/a-prime/python/get_derived_var_expr.py", line 31, in get_derived_var_expr
    print field_name, 'derived from: ', var_expr.atoms(Symbol)
UnboundLocalError: local variable 'var_expr' referenced before assignment
```

and they happen in `Pacific_$casename_TS_MAM.log` and `Pacific_$casename_TS_SON.log`.
