### ISSUE TITLE
Missing (not missing?) data for atm time-series

### ISSUE THREAD

**Issue by sterlingbaldwin** [E3SM-Project/a-prime#37]
The RESTROM, FLNT, and FSNT timeseries plots give me the following error on acme1:

```
Using file:  /space2/diagnostics/observations/Atm/CERES-EBAF_ANN_climo.nc


/space2/diagnostics/observations/Atm/CERES-EBAF_ANN_climo.nc not found! Checking derived variables list for  FLUT

No derived variable list found for  FLUT

FLUT derived from:
Traceback (most recent call last):
  File "python/plot_multiple_reg_seasonal_avg.py", line 294, in <module>
    debug = debug)
  File "python/plot_multiple_reg_seasonal_avg.py", line 95, in plot_multiple_reg_seasonal_avg
    debug = debug)
  File "/p/cscratch/acme/data/a-prime/python/get_reg_avg_climo.py", line 43, in get_reg_avg_climo
    debug = debug)
  File "/p/cscratch/acme/data/a-prime/python/read_climo_file.py", line 59, in read_climo_file
    var_expr, var_expr_numpy = get_derived_var_expr(field_name)
  File "/p/cscratch/acme/data/a-prime/python/get_derived_var_expr.py", line 31, in get_derived_var_expr
    print field_name, 'derived from: ', var_expr.atoms(Symbol)
UnboundLocalError: local variable 'var_expr' referenced before assignment
```

Which is strange since when I check, the file is there and has the correct permissions. When I check the code in get_derived_var_expr, I see that there is no case to handle FLUT which explains the UnboundLocalError exception. 

```
    if field_name == 'PRECT':
        PRECC, PRECL = symbols('PRECC, PRECL')
        var_expr = PRECC + PRECL
    elif field_name == 'RESTOM':
        FSNT, FLNT = symbols('FSNT, FLNT')
        var_expr = FSNT - FLNT
    elif field_name == 'FLNS':
        FLUS, FLDS = symbols('FLUS, FLDS')
        var_expr = FLUS - FLDS
    elif field_name == 'RESSURF':
        FLNS, FSNS, LHFLX, SHFLX = symbols('FLNS, FSNS, LHFLX, SHFLX')
        var_expr = FLNS - FSNS + LHFLX + SHFLX
    else:
        print
        print 'No derived variable list found for ', field_name

    print
    print field_name, 'derived from: ', var_expr.atoms(Symbol)
```

After checking the rest of the plots, it looks like this is the case for all the CERES-EBAF timeseries plots, they all fail to find /space2/diagnostics/observations/Atm/CERES-EBAF_ANN_climo.nc.

**Comment by xylar** [comment]
@salilmahajan, this looks like the same issue we had seen at NERSC.  Was this resolved by updating the files?  If so, we should make sure the same files get transferred to acme1.  If the solution was something else, how can we duplicate it on acme1?

**Comment by sterlingbaldwin** [comment]
I've only tried it with the files in place, I'll copy over the files at nersc and give it a shot tomorrow.

**Comment by xylar** [comment]
@sterlingbaldwin, before you do that, it might be worth contacting @salilmahajan directly.  It would be better to find out for sure from him what the issue is.

**Comment by salilmahajan** [comment]
Yes, this seems to be the same issue and we resolved it by updating the netcdf files. The files had some missing/incosistent attributes. Yes, @sterlingbaldwin, please try it again on acme1 after copying files from NERSC at: /global/project/projectdirs/acme/observations/Atm to check if that solves the issue for you.

**Comment by milenaveneziani** [comment]
@salilmahajan told me that you won't need those files. He just used them for debugging.

**Comment by sterlingbaldwin** [comment]
ok, never mind then. Im running again with a copy of the data from nersc, will report back if this fixes the issue, thanks for your help.

**Comment by salilmahajan** [comment]
Yes, @milenaveneziani is correct. A-Prime does not use those files.

**Comment by sterlingbaldwin** [comment]
Everything seems to be working with the data from NERSC. I created a backup just in case, under /space2/diagnostics/observations/Atm/data_backup

**Comment by sterlingbaldwin** [comment]
Just as a heads up, there was also data missing from the /space2/diagnostics/observations/Ocean directory. It might be worth it to check the other supported machines to make sure all the obs datasets are up to date.

**Comment by milenaveneziani** [comment]
ok, thanks for letting us know. We haven't tested a-prime on the LLNL machines in some time, due to the fact that our credentials keep expiring for some reason. But we'll do proper testing and verification before the last release.
