### ISSUE TITLE
Important config options not being set for ocean diagnostics

### ISSUE THREAD

**Issue by xylar** [E3SM-Project/a-prime#39]
It appears that `[input]/mappingDirectory` and `[regions]/regionMaskDirectory` are not being set by a-prime.  As a result, all mapping files are being generated on the fly even when they already exist in a directory that *should* be being pointed to in the config file (see #38).  Presumably the MOC plots cannot be working properly without the region mask directory having been set.

The file that needs to be updated is:
https://github.com/E3SM-Project/a-prime/blob/master/python/setup_ocnice_config.py

**Comment by xylar** [comment]
Okay, great! Glad this is on your radar. This is the main issue in #38 so should be addressed sooner rather than later to not cause issues or require nasty workarounds in processflow. Hopefully, we can combine this with MPAS-Analysis v1...

**Comment by milenaveneziani** [comment]
Addressed by #40
