### ISSUE TITLE
python 3 support

### ISSUE THREAD

**Issue by xylar** [E3SM-Project/a-prime#43]
Hey @salilmahajan (cc @milenaveneziani, @kevans32 @jhkennedy), just wondering what the timeline might be for moving over the python 3 here (if any)?  We're talking of dropping python 2 support in MPAS-Analysis sometime not too long from now and xarray has already started moving in that direction.  So libraries needed by e3sm-unified will gradually stop being supported in python 2 in the next several months.  It might become impossible to run a-prime with newer versions of e3sm-unified without python 3 support.

**Comment by salilmahajan** [comment]
Hi @xylar, yes I did hear about it. The libraries that the atm side of A-Prime uses are mostly numpy, scipy.stats, option parser, matplotlib and basemap. I know basemap is not supported by python3. Do you think these other ones would need attention too? I will come up with a timeline for basemap and any others soon.

**Comment by xylar** [comment]
@salilmahajan, I'm aware that basemap is being phased out (in both python 2 and python 3) in favor of cartopy but it does currently work in all python 3 versions I've used (3.5 to 3.7) so that shouldn't be an issue.  Still, you should work toward using cartopy instead of basemap.  All of the other libraries you list are definitely available in python 3.
